# Generated by Django 3.1 on 2024-12-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_ott_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ott',
            old_name='url',
            new_name='movieurl',
        ),
        migrations.AddField(
            model_name='ott',
            name='trailerurl',
            field=models.URLField(default='https://default-url.com'),
        ),
    ]
