# Generated by Django 3.1 on 2024-12-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_movie_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='barcode_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
