# Generated by Django 3.1 on 2024-12-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_ticket_barcode_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='barcode_data',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
